#!/usr/bin/env ruby

msg_file = ARGV[0]
msg = File.read(msg_file)

regex = /(close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved)\s*#\d+/
if regex.match(msg)
  puts '[POLICY] Your commit message contains `autoclose issue` token. Please remove it.
  Reference: https://help.github.com/articles/closing-issues-via-commit-messages'
  exit 1
end

regex = /fix.*comment/
if regex.match(msg)
  puts '[POLICY] `fix comment` is poor meaning word. Please improve commit message.'
  exit 1
end
